#! /bin/sh
# /etc/init.d/rockgame

### BEGIN INIT INFO
# Provides:          rockgame
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start rocking motorcycle at boot
# Description:       RockingMotorcylce.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting rocking motorcycle game"
    # run application you want to start
    python3 /home/pi/rockingMotorcycle/start.py &
    ;;
  stop)
    echo "Stopping rocking motorcycle game"
    # kill application you want to stop
    killall start.py
    ;;
  *)
    echo "Usage: /etc/init.d/rockgame {start|stop}"
    exit 1
    ;;
esac

exit 0

